### ISSUE TITLE
Report problems

### ISSUE THREAD

**Issue by callimac-o** [JKBert/knoda5#2]
Ciao JKB,

Thank you for your answer. I enclose two screenshots related to the problem with reports.
I'm sorry this application is dying I have been using it for my accounting since 2004 and I find it very well done. I always search on the net but I can't find a similar one unless I go back to using Microsoft access.
Other issues I have talked about are installation related and if it would be helpful for someone like me who is impractical with compiling, I can submit them.
If I can be useful in some way for the project, gladly, even if unfortunately I am not very familiar with programming, I only know python and sql that I use with knoda; I also did the Italian translation of the messages.
Ciao grazie Callimaco

![Screenshot_20211115_122916](https://user-images.githubusercontent.com/94168790/141824947-80aae7d7-e38a-4fba-80a5-2eea4a26a541.png)
![Screenshot_20211115_122959](https://user-images.githubusercontent.com/94168790/141824951-98e4d611-9557-4c1e-bfc4-d76155e105ed.png)

**Comment by callimac-o** [comment]
First screenshot, the design panel that works fine, the second when i push view button

**Comment by JKBert** [comment]
I will try to fix this issue but knoda and hkc are both bullshit pieces of C++ codes (and hkc triggers a g++ internal error in compilation process). Did this feature work with older versions ? I have converted some code to be C++11 compatible. Maybe I have done somewhere a mistake.

**Comment by callimac-o** [comment]
Hello,
I upgraded my Debian distribution from 9 to 11. Now the report preview works. For actual printing, the printer name must be entered in the print command setting.
Hi thanks for your work.
